# Generated by Django 4.2.5 on 2023-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('In Codereview', 'In Codereview'), ('Testing', 'Testing'), ('Rolled Out', 'Rolled Out')], max_length=15),
        ),
    ]
